// StormPower_Project/src/Components/Header.jsx
function Header() {
  return (
    <header className="navbar navbar-expand-lg d-flex justify-content-start align-items-baseline py-5">
      <h1 className="m-0">
        <a href="#" className="text-decoration-none fw-bold text-white display-3 m-5">
          Storm Power
        </a>
      </h1>
      <nav>
        <ul className="navbar-nav ms-auto">
          {["Home", "About", "Plans", "Contact"].map((item, i) => (
            <li key={i} className="nav-item me-3 fs-6">
              <a href="#" className="text-decoration-none fw-bold text-white">
                {item}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// Harmony/src/components/Header.svelte
<header>
  <h1><a href="#" class="link">Harmony</a></h1>
  <nav>
    <ul>
      <li><a href="#" class="link">About</a></li>
      <li><a href="#" class="link">Github</a></li>
    </ul>
  </nav>
</header>

<style lang="scss">
  header {
    display: flex;
    justify-content: space-around;
    align-items: flex-end;
    padding: 1rem;

    h1 {
      font-size: 2.2rem;
    }
    
    ul {
      list-style: none;
      li {
        display: inline-block;
        a {
          font-size: 1rem;
          border-bottom: 1px solid transparent;
          &:hover {
          border-bottom: 1px solid #fff;
          }
        }
      }
    }

  }

.link {
      color: #fff;
      text-decoration: none;
  }

</style>
