// Harmony/src/components/Header.svelte
<header>
  <h1><a href="/" class="link">Harmony</a></h1>
  <nav>
    <ul>
      <li><a href="/" class="link">Home</a></li>
      <li><a href="/" class="link">About</a></li>
      <li><a href="/" class="link">Github</a></li>
    </ul>
  </nav>
</header>

<style lang="scss">
  header {
    position: fixed;
    display: flex;
    justify-content: space-around;
    align-items: flex-end;
    padding: 1rem;
    width: 100%;

    h1 {
      font-size: 3rem;
    }
    
    ul {
      list-style: none;
      li {
        display: inline-block;
        margin-left: 5px;
        a {
          font-size: 1rem;
          border-bottom: 1px solid transparent;
          transition: 1s;
          &:hover {
          border-bottom: 1px solid;
          }
        }
      }
    }
  }

.link {
      text-decoration: none;
  }

</style>

// StromPower_Project/src/Components/Header.jsx
function Header() {
  return (
    <header
      className="d-flex justify-content-start align-items-center pt-5"
      style={{ backgroundColor: "transparent", height: "150px"}}
    >
      <h1>
        <a
          href="#"
          className="text-decoration-none fw-bold text-white"
          style={{ fontSize: "1.2em", margin: "2em" }}
        >
          Storm Power
        </a>
      </h1>
      <nav className="navbar navbar-expand-lg">
        <ul className="navbar-nav">
          {["Home", "About", "Plans", "Contact"].map((item, i) => (
            <li key={i} className="nav-item me-3 fs-6">
              <a href="#" className="text-decoration-none fw-bold text-white">
                {item}
              </a>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}

export default Header;
